
CREATE TABLE kunden (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  firma VARCHAR(255) NULL,
  vorname VARCHAR(255) NULL,
  nachname VARCHAR(255) NULL,
  strasse VARCHAR(255) NULL,
  plz VARCHAR(255) NULL,
  ort VARCHAR(255) NULL,
  land VARCHAR(255) NULL,
  telefon VARCHAR(255) NULL,
  fax VARCHAR(255) NULL,
  mobil VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  homepage VARCHAR(255) NULL,
  bank VARCHAR(255) NULL,
  kto VARCHAR(255) NULL,
  blz VARCHAR(255) NULL,
  inhaber VARCHAR(255) NULL,
  iban VARCHAR(255) NULL,
  bic VARCHAR(255) NULL,
  notizen VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE lieferanten (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  firma VARCHAR(255) NULL,
  vorname VARCHAR(255) NULL,
  nachname VARCHAR(255) NULL,
  strasse VARCHAR(255) NULL,
  plz VARCHAR(255) NULL,
  ort VARCHAR(255) NULL,
  land VARCHAR(255) NULL,
  telefon VARCHAR(255) NULL,
  fax VARCHAR(255) NULL,
  mobil VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  homepage VARCHAR(255) NULL,
  bank VARCHAR(255) NULL,
  kto VARCHAR(255) NULL,
  blz VARCHAR(255) NULL,
  inhaber VARCHAR(255) NULL,
  iban VARCHAR(255) NULL,
  bic VARCHAR(255) NULL,
  notizen VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE einzelperson (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  firma VARCHAR(255) NULL,
  vorname VARCHAR(255) NULL,
  nachname VARCHAR(255) NULL,
  strasse VARCHAR(255) NULL,
  plz VARCHAR(255) NULL,
  ort VARCHAR(255) NULL,
  land VARCHAR(255) NULL,
  telefon VARCHAR(255) NULL,
  fax VARCHAR(255) NULL,
  mobil VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  geburtstag DATE NULL,
  familienstand VARCHAR(255) NULL,
  nationalitaet VARCHAR(255) NULL,
  beruf VARCHAR(255) NULL,
  bank VARCHAR(255) NULL,
  kto VARCHAR(255) NULL,
  blz VARCHAR(255) NULL,
  inhaber VARCHAR(255) NULL,
  iban VARCHAR(255) NULL,
  bic VARCHAR(255) NULL,
  notizen VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE kosten (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  gruppe VARCHAR(255) NULL,
  art VARCHAR(255) NULL,
  geplant INTEGER UNSIGNED NULL,
  tatsaechlich INTEGER UNSIGNED NULL,
  PRIMARY KEY(id)
);

CREATE TABLE presse (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  vorname VARCHAR(255) NULL,
  nachname VARCHAR(255) NULL,
  strasse VARCHAR(255) NULL,
  plz VARCHAR(255) NULL,
  ort VARCHAR(255) NULL,
  land VARCHAR(255) NULL,
  telefon VARCHAR(255) NULL,
  fax VARCHAR(255) NULL,
  mobil VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  notizen VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE showband (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  firma VARCHAR(255) NULL,
  vorname VARCHAR(255) NULL,
  nachname VARCHAR(255) NULL,
  strasse VARCHAR(255) NULL,
  plz VARCHAR(255) NULL,
  ort VARCHAR(255) NULL,
  land VARCHAR(255) NULL,
  telefon VARCHAR(255) NULL,
  fax VARCHAR(255) NULL,
  mobil VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  homepage VARCHAR(255) NULL,
  bank VARCHAR(255) NULL,
  kto VARCHAR(255) NULL,
  blz VARCHAR(255) NULL,
  inhaber VARCHAR(255) NULL,
  iban VARCHAR(255) NULL,
  bic VARCHAR(255) NULL,
  notizen VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE veranstalter (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  firma VARCHAR(255) NULL,
  vorname VARCHAR(255) NULL,
  nachname VARCHAR(255) NULL,
  strasse VARCHAR(255) NULL,
  plz VARCHAR(255) NULL,
  ort VARCHAR(255) NULL,
  land VARCHAR(255) NULL,
  telefon VARCHAR(255) NULL,
  fax VARCHAR(255) NULL,
  mobil VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  homepage VARCHAR(255) NULL,
  bank VARCHAR(255) NULL,
  kto VARCHAR(255) NULL,
  blz VARCHAR(255) NULL,
  inhaber VARCHAR(255) NULL,
  iban VARCHAR(255) NULL,
  bic VARCHAR(255) NULL,
  notizen VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE veranstaltungen (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  preis INTEGER UNSIGNED NULL,
  typ VARCHAR(255) NULL,
  liste VARCHAR(255) NULL,
  budget INTEGER UNSIGNED NULL,
  stat INTEGER UNSIGNED NULL,
  optioniert VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE veranstaltungsort (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  vorname VARCHAR(255) NULL,
  nachname VARCHAR(255) NULL,
  strasse VARCHAR(255) NULL,
  plz VARCHAR(255) NULL,
  ort VARCHAR(255) NULL,
  land VARCHAR(255) NULL,
  telefon VARCHAR(255) NULL,
  fax VARCHAR(255) NULL,
  mobil VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  homepage VARCHAR(255) NULL,
  bank VARCHAR(255) NULL,
  kto VARCHAR(255) NULL,
  blz VARCHAR(255) NULL,
  inhaber VARCHAR(255) NULL,
  iban VARCHAR(255) NULL,
  bic VARCHAR(255) NULL,
  notizen VARCHAR(255) NULL,
  PRIMARY KEY(id)
);


